#!/bin/bash -x
<?php	

error_reporting(E_ALL);
date_default_timezone_set('UTC');

  	 $restrict_mods = array('api' => true);
    if (!@include_once(getenv('FREEPBX_CONF') ? getenv('FREEPBX_CONF') : '/etc/freepbx.conf')) {
            include_once('/etc/asterisk/freepbx.conf');
    }
	 $freepbx = FreePBX::Api();

	 if (isset($argv[1])) {
        // Underp the base64
        $b = str_replace('_', '/', $argv[1]);
        $settings = @json_decode(gzuncompress(@base64_decode($b)), true);
        dbug($settings);
        if (is_array($settings)) {
                $module = $settings[0];
					 $action = $settings[1];
					 $track = $settings[2];
					 $txnId = $settings[3];
        }
	 }

	$bin = \FreePBX::Config()->get('AMPSBIN');
	
	$cmd = $bin.'/fwconsole ma '.$action.' '.$module.' '.$track;
	exec($cmd, $output[0]);
	$output = json_encode($output);

	if(!empty(output)){
		 $freepbx->setTransactionStatus($txnId,'Executed',$output);
	}else{
		 $freepbx->setTransactionStatus($txnId,'Failed',$output);
	}

   